export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <div className="prose lg:prose-xl mx-auto">
        <h1>Terms of Service</h1>
        <p><strong>Last updated:</strong> {new Date().toLocaleDateString()}</p>
        
        <p>Please read these Terms of Service carefully before using the ResumeRender website.</p>
        
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using our website, you accept and agree to be bound by the terms and provision of this agreement. In addition, when using our particular services, you shall be subject to any posted guidelines or rules applicable to such services.</p>
        
        <h2>2. Description of Service</h2>
        <p>ResumeRender provides users with tools to build resumes online. This includes free and paid templates, AI-assisted content generation, and download functionalities (PDF, Image). All data entered by the user is stored locally on the user's browser and not on our servers.</p>

        <h2>3. Payments and Refunds</h2>
        <p>Certain features of the Service, such as premium resume templates, are available for a one-time fee. All payments are processed through our third-party payment processor, Razorpay. All sales are final, and we do not offer refunds once a template has been purchased and access to the editor has been granted.</p>

        <h2>4. Use of AI Content</h2>
        <p>The content generated by our AI is intended as a suggestion and a starting point. You are solely responsible for the final content of your resume and for ensuring its accuracy and appropriateness. ResumeRender is not liable for any inaccuracies or for the effectiveness of the generated content in your job search.</p>

        <h2>5. Intellectual Property</h2>
        <p>The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of ResumeRender and its licensors. Our templates are provided for your personal, non-commercial use only.</p>

        <h2>6. Limitation of Liability</h2>
        <p>In no event shall ResumeRender, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
        
        <h2>7. Changes to Terms</h2>
        <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms of Service on this page.</p>
      </div>
    </div>
  );
}
